BASE = ../../ucoolib

TARGETS = stm32f4
# stm32f4_PROGS = rgb servo
# stm32f4_PROGS = rgb
stm32f4_PROGS = servo
servo_SOURCES = test_servo.stm32f4.cc
# rgb_SOURCES = test_rgb.stm32f4.cc

MODULES = hal/gpio hal/usb utils

include $(BASE)/build/top.mk

